version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: order_postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=orderdb
    volumes:
      - postgres_data:/var/lib/psotgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: order_redis
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: order_rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" #Management UI

volumes:
  postgres_data: