basePath: /
definitions:
  model.Product:
    properties:
      description:
        type: string
      id:
        type: integer
      in_stock:
        type: boolean
      name:
        type: string
      price:
        type: number
    type: object
host: localhost:8081
info:
  contact: {}
  description: REST APIs for managing products
  title: Product Service API
  version: "1.0"
paths:
  /products:
    get:
      description: Retrieve all products from the catalog
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Product'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all products
      tags:
      - Products
    post:
      consumes:
      - application/json
      description: Add a new product to the catalog
      parameters:
      - description: Product to create
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/model.Product'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Product'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new product
      tags:
      - Products
swagger: "2.0"
